
# 合并本地 CLIP、远程 CLIP

from .local_CLIP_node import (
    NODE_CLASS_MAPPINGS as LOCAL_CLIP_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOCAL_CLIP_DISPLAY_MAPPINGS,
)

from .Remote_CLIP_node import (
    NODE_CLASS_MAPPINGS as REMOTE_CLIP_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as REMOTE_CLIP_DISPLAY_MAPPINGS,
)



# 统一合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LOCAL_CLIP_MAPPINGS)
NODE_CLASS_MAPPINGS.update(REMOTE_CLIP_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LOCAL_CLIP_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(REMOTE_CLIP_DISPLAY_MAPPINGS)


__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
